spring.application.name=emailSender


#Email properties
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hlayisekomalucks@gmail.com
spring.mail.password=mlwtqmewzqoqfccm
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
application.mail.from-email=hlayisekomalucks@gmail.com
application.email.from-name=no-reply
application.receptionist.email=hlungwanintsetselelo@gmail.com
